### ISSUE TITLE
Force top block too.

### ISSUE THREAD

**Issue by RDKRACZ** [SFort/MC-lengthyladders#4]
You made it so the only required block for ladders to not break is the ground block. Can you add a config to also require a "top" block? The ladder has to be leaning on something, right?

![2021-04-10_14 20 56](https://user-images.githubusercontent.com/43277609/114269871-80ba2c80-9a09-11eb-8b76-5cc5e5b919a5.png)

**Comment by SFort** [comment]
Reason why this was done was because in order to have both at once i would need to do one of the following:
- Change the ladder to a TileEntity (No longer making this a server-side mod)
- Allow for floating ladders
- cause block updates for all the ladders everytime a neighbour updates
and those options kinda suck for performance or compatability

And honestly mods that add rope ladders kinda handle that functionality already so i didn't think it a big deal

**Comment by RDKRACZ** [comment]
Ah, if that's the case feel free to close.
